query MainLayout($locales: [Locale!]!) {
	layout(where: { name: "Main Layout" }, locales: $locales) {
		id
		name
		locale
		headerLinks {
			id
			locale
			name: key
			link: value
		}
		headerCta {
			id
			locale
			name: key
			link: value
		}
		footerSentence
		footerLinks {
			id
			locale
			title
			link {
				id
				locale
				key
				value
			}
		}
		rights
	}
}
