query Home($locales: [Locale!]!) {
  homePage(where: {id: "clq6sh5rsbbyb0bl521rzk9f7"}, locales: $locales) {
    locale
    heading
    subHeading
    cta {
      id
      locale
      label: key
      link: value
    }
    servicesTag
    servicesTitle
    servicesDescription
    services {
      locale
      id
      title
      description
    }
    testimony {
      locale
      id
      name
      testimony
      position
    }
    toolsTitle
    toolsDescription
    blogPostsTitle
    blogPostsDescription
    callOut {
      locale
      id
      heading
      subHeading
      cta
    }
  }
  blogPosts(first: 3, orderBy: updatedAt_DESC, locales: $locales) {
    locale
    id
    tag
    name
    description
    url
    cta
  }
}
