query BlogPost($slug: String, $language:Locale!) {
  blogPosts(where: {url_contains: $slug}, locales: [$language, en]) {
    id
    name
    tag
    heroImage {
      alt
      url
      metadata
    }
    intro
    mainHeading
    content {
      html
    }
  }
}
